# bunx markdownlint-cli2 --fix .

default: true

MD013:
  line_length: 140
  heading_line_length: 140
  code_block_line_length: 140
  code_blocks: true
  tables: true
  headings: true
  strict: false
  stern: false

MD035:
  style: "---"