name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New package version'
        required: true

permissions:
  contents: write

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update version
        run: |
          OLD_VERSION=$(grep ^version pyproject.toml | cut -d '"' -f 2)
          OLD_VERSION="\"$OLD_VERSION\""
          sed -i "s+version = $OLD_VERSION+version = ${{ github.event.inputs.version }}+g" pyproject.toml
      - name: Build and publish to private repository
        uses: JRubics/poetry-publish@v2.0
        with:
          repository_url: ${{ secrets.PYPI_URL }}
          repository_username: ${{ secrets.PYPI_LOGIN }}
          repository_password: ${{ secrets.PYPI_PASSWORD }}
          poetry_install_options: --without dev
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "action: update version"
          git push